Name: Shahnwaz Khan
Roll: AC-1272
Program: KNN Classifier

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

In [2]:
# df=pd.read_csv('C:/Users/91914/OneDrive/Documents/6th_Semester/ML/Data.csv')
import seaborn as sns
df=sns.load_dataset('iris')
display(df.head())

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# Preprocessing: Fill missing values
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
# store the feature matrix (X) and response vector (y)
X = df.drop(columns='species')
y = df['species']
# splitting X and y into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
  

In [7]:
x_train

sepal_length  sepal_width  petal_length  petal_width
83            6.0          2.7           5.1          1.6
27            5.2          3.5           1.5          0.2
139           6.9          3.1           5.4          2.1
149           5.9          3.0           5.1          1.8
98            5.1          2.5           3.0          1.1
..            ...          ...           ...          ...
96            5.7          2.9           4.2          1.3
88            5.6          3.0           4.1          1.3
115           6.4          3.2           5.3          2.3
19            5.1          3.8           1.5          0.3
81            5.5          2.4           3.7          1.0

[120 rows x 4 columns]

In [8]:
y_train

83     versicolor
27         setosa
139     virginica
149     virginica
98     versicolor
          ...    
96     versicolor
88     versicolor
115     virginica
19         setosa
81     versicolor
Name: species, Length: 120, dtype: object

In [9]:
# Create an instance of KNN class. Neighbors size=5 and p=2 means use Euclidean distance 
classifier=KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)

In [10]:
# Train our data by fitting the data into our model
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [11]:
# Now predict the output
y_pred=classifier.predict(x_test)

In [12]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.86      1.00      0.92        12
   virginica       1.00      0.75      0.86         8

    accuracy                           0.93        30
   macro avg       0.95      0.92      0.93        30
weighted avg       0.94      0.93      0.93        30



In [14]:
# Confusion metrics
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
# print(precision_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(cm)

0.9333333333333333
[[10  0  0]
 [ 0 12  0]
 [ 0  2  6]]


In [15]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.9333333333333333
