Name: Shahnwaz Khan
Roll: AC-1272
Program: Logistic Regression Classifier

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [1]:
# df=pd.read_csv('C:/Users/91914/OneDrive/Documents/6th_Semester/ML/Data.csv')
import seaborn as sns
df=sns.load_dataset('iris')
display(df.head())

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
# Preprocessing: Fill missing values
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [4]:
# store the feature matrix (X) and response vector (y)
X = df.drop(columns='species')
y = df['species']
# splitting X and y into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
x_train

sepal_length  sepal_width  petal_length  petal_width
31            5.4          3.4           1.5          0.4
141           6.9          3.1           5.1          2.3
133           6.3          2.8           5.1          1.5
21            5.1          3.7           1.5          0.4
73            6.1          2.8           4.7          1.2
..            ...          ...           ...          ...
16            5.4          3.9           1.3          0.4
62            6.0          2.2           4.0          1.0
139           6.9          3.1           5.4          2.1
22            4.6          3.6           1.0          0.2
124           6.7          3.3           5.7          2.1

[120 rows x 4 columns]

In [6]:
y_train

31         setosa
141     virginica
133     virginica
21         setosa
73     versicolor
          ...    
16         setosa
62     versicolor
139     virginica
22         setosa
124     virginica
Name: species, Length: 120, dtype: object

In [7]:
# Create an object of LogisticRegression
LR=LogisticRegression()

In [8]:
# Train the model
LR.fit(x_train,y_train)

LogisticRegression()

In [9]:
y_pred=LR.predict(x_test)

In [10]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.92      1.00      0.96        11
   virginica       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [11]:
# Confusion metrics
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
# print(precision_score(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(cm)

0.9666666666666667
[[10  0  0]
 [ 0 11  0]
 [ 0  1  8]]
